# Scraping

In [31]:
import yfinance as yf
import pandas as pd
import numpy as np

In [32]:
tickers = ['TCS.NS', 'HDFCBANK.NS', 'RELIANCE.NS', 'SUNPHARMA.NS', 'ITC.NS']
print("Downloading data")
data = yf.download(tickers, start = "2014-01-01", end = "2023-12-31")['Close']
data.head()

[*********************100%***********************]  5 of 5 completed

Downloading data

Ticker      HDFCBANK.NS      ITC.NS  RELIANCE.NS  SUNPHARMA.NS      TCS.NS
Date
2014-01-01   150.498566  138.952728   188.334061    523.221313  811.153198
2014-01-02   148.654556  135.741791   185.409897    524.592712  816.314148
2014-01-03   150.034714  135.655609   183.131989    529.940491  837.108093
2014-01-06   149.717972  136.043488   181.161377    537.756775  843.662598
2014-01-07   150.328873  136.496048   178.438477    543.195862  831.061646

In [33]:
print(f"Number of missing values: {data.isna().sum().sum()}")

returns = data.dropna()
returns.head()

Number of missing values: 0

Ticker      HDFCBANK.NS      ITC.NS  RELIANCE.NS  SUNPHARMA.NS      TCS.NS
Date
2014-01-01   150.498566  138.952728   188.334061    523.221313  811.153198
2014-01-02   148.654556  135.741791   185.409897    524.592712  816.314148
2014-01-03   150.034714  135.655609   183.131989    529.940491  837.108093
2014-01-06   149.717972  136.043488   181.161377    537.756775  843.662598
2014-01-07   150.328873  136.496048   178.438477    543.195862  831.061646

In [34]:
print("Annualised Expected Returns:")
mean_returns = returns.mean() * 252
print(mean_returns)

Annualised Expected Returns:
Ticker
HDFCBANK.NS     121537.302925
ITC.NS           49595.506478
RELIANCE.NS     153793.455946
SUNPHARMA.NS    167506.075687
TCS.NS          459607.828677
dtype: float64

In [35]:
print("Annualised Risk: ")
std_returns = returns.std() * np.sqrt(252)
print(std_returns)

Annualised Risk:
Ticker
HDFCBANK.NS      3249.997015
ITC.NS           1070.120781
RELIANCE.NS      5981.800300
SUNPHARMA.NS     3248.153805
TCS.NS          14060.754394
dtype: float64

In [36]:
cov_matrix = returns.cov() * 252
print("Annualised Covariance Matrix\n")
print(cov_matrix)

Annualised Covariance Matrix

Ticker         HDFCBANK.NS        ITC.NS   RELIANCE.NS  SUNPHARMA.NS  \
Ticker
HDFCBANK.NS   1.056248e+07  2.228996e+06  1.839875e+07  2.674916e+06
ITC.NS        2.228996e+06  1.145158e+06  3.960515e+06  2.095897e+06
RELIANCE.NS   1.839875e+07  3.960515e+06  3.578193e+07  7.338654e+06
SUNPHARMA.NS  2.674916e+06  2.095897e+06  7.338654e+06  1.055050e+07
TCS.NS        4.305222e+07  9.123663e+06  8.199081e+07  1.991409e+07

Ticker              TCS.NS
Ticker
HDFCBANK.NS   4.305222e+07
ITC.NS        9.123663e+06
RELIANCE.NS   8.199081e+07
SUNPHARMA.NS  1.991409e+07
TCS.NS        1.977048e+08

In [37]:
# Save data to CSV 
returns.to_csv('stock_data.csv')
mean_returns.to_csv('mean_returns.csv')
std_returns.to_csv('std_returns.csv')
cov_matrix.to_csv('cov_matrix.csv')